sonar.projectKey=CatLedger
sonar.projectName=CatLedger
sonar.sources=CatLedger/
sonar.tests=CatLedgerTests/
sonar.swift.swiftlint.reportPaths=sonar-reports/swiftlint.json
sonar.host.url=http://localhost:9000
